language_enabled_php: true
language_tags_php: '<php>'
language_enabled_drupal5: true
language_tags_drupal5: '<drupal5>'
language_enabled_drupal6: true
language_tags_drupal6: '<drupal6>'
language_enabled_javascript: true
language_tags_javascript: '<javascript>'
language_enabled_java: true
language_tags_java: '<java>'
language_enabled_c: true
language_tags_c: '<c>'
language_enabled_cpp: true
language_tags_cpp: '<cpp>'
language_enabled_python: true
language_tags_python: '<python>'
language_enabled_ruby: true
language_tags_ruby: '<ruby>'
